apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-ai
  namespace: devterview
  labels:
    app: dv-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dv-ai
  template:
    metadata:
      labels:
        app: dv-ai
    spec:
      containers:
      - name: dv-ai
        image: prunsoli/dv-ai:0.0.1
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: dv-ai-secret
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m" 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-ai-celery
  namespace: devterview
  labels:
    app: dv-ai-celery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dv-ai-celery
  template:
    metadata:
      labels:
        app: dv-ai-celery
    spec:
      containers:
      - name: dv-ai-celery
        image: prunsoli/dv-ai-celery:0.0.1
        envFrom:
        - secretRef:
            name: dv-ai-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"        
