apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dv-ai
  name: dv-ai
  namespace: devterview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dv-ai
  template:
    metadata:
      labels:
        app: dv-ai
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: dv-ai-secret
        image: prunsoli/dv-ai:0.0.4
        name: dv-ai
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dv-ai-celery
  name: dv-ai-celery
  namespace: devterview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dv-ai-celery
  template:
    metadata:
      labels:
        app: dv-ai-celery
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: dv-ai-secret
        image: prunsoli/dv-ai-celery:0.0.5
        name: dv-ai-celery
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
