apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dv-backend
  name: dv-backend
  namespace: devterview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dv-backend
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: dv-backend
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: prod
        envFrom:
        - secretRef:
            name: dv-back-secret
        image: prunsoli/dv-backend:0.0.3
        livenessProbe:
          httpGet:
            path: /ping-pong
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: dv-backend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
