apiVersion: v1
kind: Service
metadata:
  name: appserver-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: dv-backend
  ports:
    - port: 80
      targetPort: 8080