apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-backend
  namespace: devterview
  labels:
    app: dv-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dv-backend
  template:
    metadata:
      labels:
        app: dv-backend
      annotations:
        prometheus.io/scrape: "true"           # Prometheus 스크랩 활성화
        prometheus.io/path: "/actuator/prometheus"  # 스크랩할 경로
        prometheus.io/port: "8080"            # 스크랩할 포트
    spec:
      containers:
      - name: dv-backend
        image: prunsoli/dv-backend:93
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ping-pong
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
          - name: ENVIRONMENT
            value: prod
        envFrom:
        - secretRef:
            name: dv-back-secret
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "500m"


