apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dv-front
  name: dv-front
  namespace: devterview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dv-front
  template:
    metadata:
      labels:
        app: dv-front
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: dv-front-secret
        image: prunsoli/dv-front:0.0.1
        livenessProbe:
          httpGet:
            path: /api
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: dv-front
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
