apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-backend
  namespace: devterview
  labels:
    app: dv-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dv-backend
  template:
    metadata:
      labels:
        app: dv-backend
    spec:
      containers:
      - name: dv-backend
        image: prunsoli/dv-backend:81
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: app-secret
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "500m"