apiVersion: v1
kind: Service
metadata:
  name: frontserver-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: dv-front
  ports:
    - port: 80
      targetPort: 8080
    - port: 443
      targetPort: 8080